name: Bump SemVer Action
description: GitHub Action to bump semantic versioning based on releases or tags
author: flatherskevin
branding:
  icon: chevron-up
  color: purple

inputs:
  incrementLevel:
    required: true
    description: "Increment a version by the specified level. Can be one of: major, minor, patch, premajor, preminor, prepatch, or prerelease"
  token:
    required: true
    description: GitHub token to access API
    default: ${{ github.token }}
  prefix:
    required: false
    description: Filter versions by prefix
    default: ''
  source:
    required: false
    description: "Where to pull versions from. Can be one of: releases or tags"
    default: tags
  includePrereleases:
    required: false
    description: Include prerleases when determining the latest version to increment
    default: "false"

outputs:
  currentVersion:
    description: The current version used as a base
  nextVersion: 
    description: The new version after a semantic version bump

runs:
  using: 'node20'
  main: 'dist/index.js'
