name: Release

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.ref }}-release

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: version
        id: version
        uses: ./
        with:
          incrementLevel: patch
          source: tags
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ steps.version.outputs.nextVersion }}
          tag_name: ${{ steps.version.outputs.nextVersion }}
          token: ${{ secrets.GITHUB_TOKEN }}
      