name: Release

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.ref }}-release

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - name: version
        id: version
        uses: ./
        with:
          incrementLevel: patch
          source: tags
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ steps.version.outputs.nextVersion }}
          tag_name: ${{ steps.version.outputs.nextVersion }}
      - name: Tag new target
        run: git tag -f v1 ${{ steps.version.outputs.nextVersion }}
      - name: Push new tag
        run: git push origin v1 --force